<?xml version="1.0" encoding="utf-8"?><Database Name="DatabaseForTask" Class="LinqToSQLDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=&quot;C:\Users\Galileo\documents\visual studio 2013\Projects\FinancialFilesMergingPortal\FinancialFilesMergingPortal\App_Data\DatabaseForTask.mdf&quot;;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="FinancialFilesMergingPortal.Services.Properties.Settings" SettingsPropertyName="DatabaseForTaskConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.InputFinancialFile" Member="InputFinancialFiles">
    <Type Name="InputFinancialFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FUN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalCreditCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalCreditAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalDebitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalDebitAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PhysicalLocation" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InputFinancialFilesBatch" Member="InputFinancialFilesBatches">
    <Type Name="InputFinancialFilesBatch">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreationDateTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorDescription" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OutputFinancialFile" Member="OutputFinancialFiles">
    <Type Name="OutputFinancialFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FUN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalCreditCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalCreditAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalDebitCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalDebitAmount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhysicalDirectory" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>