//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialFilesMergingPortal.FileMergeServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileMergeServiceReference.IFinancialFilesService")]
    public interface IFinancialFilesService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialFilesService/SendData", ReplyAction="http://tempuri.org/IFinancialFilesService/SendDataResponse")]
        string SendData(string userName, byte[][] files, string[] filesNames);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFinancialFilesService/SendData", ReplyAction="http://tempuri.org/IFinancialFilesService/SendDataResponse")]
        System.Threading.Tasks.Task<string> SendDataAsync(string userName, byte[][] files, string[] filesNames);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFinancialFilesServiceChannel : FinancialFilesMergingPortal.FileMergeServiceReference.IFinancialFilesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinancialFilesServiceClient : System.ServiceModel.ClientBase<FinancialFilesMergingPortal.FileMergeServiceReference.IFinancialFilesService>, FinancialFilesMergingPortal.FileMergeServiceReference.IFinancialFilesService {
        
        public FinancialFilesServiceClient() {
        }
        
        public FinancialFilesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FinancialFilesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialFilesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FinancialFilesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendData(string userName, byte[][] files, string[] filesNames) {
            return base.Channel.SendData(userName, files, filesNames);
        }
        
        public System.Threading.Tasks.Task<string> SendDataAsync(string userName, byte[][] files, string[] filesNames) {
            return base.Channel.SendDataAsync(userName, files, filesNames);
        }
    }
}
