//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancialFilesMergingPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Security.Cryptography;

    
    public partial class User
    {
        public int Id { get; set; }
        public string Username { get; set; }
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Email { get; set; }

        public string CreatePasswordHash(string pwd)
        {
            byte[] Data = System.Text.UTF8Encoding.UTF8.GetBytes(pwd);
            SHA512Managed sha = new SHA512Managed();
            byte[] HashValue = sha.ComputeHash(Data);
            string result = string.Empty;

            foreach (var h in HashValue)
                result += string.Format("{0:X}", h);

            return result;
        }
 
    }
}
